### ISSUE TITLE
addmembers.php fails to connect to database

### ISSUE THREAD

**Issue by drinkingsouls** [DudeThatsErin/enth#1]
**Describe the bug**
addmembers.php can't connect to database.

Initially, deprecated functions stop the script from running. To solve this:
mysql_connect line 89 needs to be changed to mysqli_connect
mysql_select_db line 92 needs to be changed to mysqli_select_db
mysql_query line 94 needs to be changed to mysqli_query

Undefined variable $path line 152 causes the issue.

**To Reproduce**
1. Go to addmembers.php
2. Select fanlisting to add member
3. Input member deails and click add member

**Expected behavior**
Member is added

**Actual behavior**
Message "Cannot connect to the database. Try again." is presented.
Error log populated with:
```
/admin/addmembers.php:140 NOTICE: [8] Undefined variable: path
/admin/addmembers.php:92 WARNING: [2] mysqli_select_db() expects exactly 2 parameters, 1 given
```

**Comment by drinkingsouls** [comment]
Turns out there was quite a few issues with this file for me. It wasn't PHP 8 ready? I've made quite a few changes to get it to work. Countries were not saving save so I've used some of the code from show_join to fix that.
I'd like to add field verification too so you can't add members without a name, email and country. Could probably easily be done using code from show_join.php too.

Modified addmembers.php:
[addmembers-updated.zip](https://github.com/DudeThatsErin/enth/files/12409800/addmembers-updated.zip)

**Comment by DudeThatsErin** [comment]
Sorry about that. I tested out most of the features (I don't have a fanlisting collective or any fanlistings to test them on) and when I was using it everything _seemed_ to work fine.

I'll implement these changes this week and I'll see if I can do that verification as well.

I appreciate your help and I'll credit you in the readme upon the next update as well. 😄

**Comment by DudeThatsErin** [comment]
I have implemented both fixes! Uploading the update in after closing this.
