### ISSUE TITLE
SMTP Mail

### ISSUE THREAD

**Issue by drinkingsouls** [DudeThatsErin/enth#3]
**Describe the bug**
Cannot set mail to be sent via SMTP in Enthusiast settings.

**Issue 1**
**To Reproduce**
1. Go to admin settings.
2. Change "Mailer to use" to SMTP
3. Click "Yes, SMTP server requires authentication"

**Expected behavior**
SMTP settings and authentication setting is saved.

**Actual behavior**
"Yes, SMTP server requires authentication" unticks itself and is not saved in the database.
The smtp_auth column does not exist.

**Workaround**
Add the  the smtp_auth column into the settings table directly with the value "yes".

**Issue 2**
**To Reproduce**
1. Join a fanlisting from the front end as a member.

**Expected behavior**
Join email is sent.

**Actual behavior**
Join form is processed but no success message is displayed and no email is sent.
error_log populated with:
PHP Fatal error:  Uncaught Error: Class 'Net_SMTP' not found in /home/site/admin/Mail/smtp.php:366
File to include on previous line 365 "include_once 'Net/SMTP.php';" doesn't exist in the script.

**Additional Details**
Net_SMTP is installed at my host.
It seems the file Net/SMTP.php has not been present in Enthusiast for a long time. Check [this thread](https://community.x10hosting.com/threads/smtp-sendmail.163261/) from 2011.

**General Workaround**
I've used Sendmail which seems to work fine once the  smtp_auth column and value has been added to the database.

**Comment by DudeThatsErin** [comment]
Please see the notice on the repo, I am no longer maintaining these.
